### ISSUE TITLE
Good job ! 

### ISSUE THREAD

**Issue by Trangle12** [RikoLi/PCL-CLIP#1]
Congratulations on your new result. The paper inside combined with unsupervised ReID also achieved very satisfactory results, and I see that experiments are also conducted inside combined with ClusterContrast, will the code of this part be released? Finally, I hope your paper achieves good results.

**Comment by Trangle12** [comment]
The code is clearly written and easy to understand, I've finished the unsupervised code changes, thanks again for your work!

**Comment by minnie-lin** [comment]
> The code is clearly written and easy to understand, I've finished the unsupervised code changes, thanks again for your work!

请问无监督的该如何修改呢？

**Comment by minnie-lin** [comment]
> 代码写得很清楚，很容易理解，我已经完成了无监督的代码修改，再次感谢您的工作！

你好，请问你修改之后对于MSMT数据集能够很好完成工作吗

**Comment by Trangle12** [comment]
不好意思，刚看到消息，我的是在MSMT17上实验的，效果还是可以的，和论文里面基本上一致的。我在ClusterContrast中设置如下：1、Freeze patch projection layer trick 2、DBSCAN 0.7 30 6   3、将Adam修改为SGD 优化器

**Comment by Trangle12** [comment]
> > 代码写得很清楚，很容易理解，我已经完成了无监督的代码修改，再次感谢您的工作！
> 
> 你好，请问你修改之后对于MSMT数据集能够很好完成工作吗

不好意思，刚看到消息，我的是在MSMT17上实验的，效果还是可以的，和论文里面基本上一致的。我在ClusterContrast中设置如下：1、Freeze patch projection layer trick 2、DBSCAN 0.7 30 6 3、将Adam修改为SGD 优化器

**Comment by minnie-lin** [comment]
> > > 代码写得很清楚，很容易理解，我已经完成了无监督的代码修改，再次感谢您的工作！
> > 
> > 
> > 你好，请问你修改之后对于MSMT数据集能够很好完成工作吗
> 
> 不好意思，刚看到消息，我的是在MSMT17上实验的，效果还是可以的，和论文里面基本上一致的。我在ClusterContrast中设置如下：1、Freeze patch projection layer trick 2、DBSCAN 0.7 30 6 3、将Adam修改为SGD 优化器

@Trangle12 你好，我也是这么设置的，然后优化器两个都试了，还是很低，很冒昧的想看看你修改后的代码可以吗

**Comment by Trangle12** [comment]
> > > > 代码写得很清楚，很容易理解，我已经完成了无监督的代码修改，再次感谢您的工作！
> > > 
> > > 
> > > 你好，请问你修改之后对于MSMT数据集能够很好完成工作吗
> > 
> > 
> > 不好意思，刚看到消息，我的是在MSMT17上实验的，效果还是可以的，和论文里面基本上一致的。我在ClusterContrast中设置如下：1、Freeze patch projection layer trick 2、DBSCAN 0.7 30 6 3、将Adam修改为SGD 优化器
> 
> @Trangle12 你好，我也是这么设置的，然后优化器两个都试了，还是很低，很冒昧的想看看你修改后的代码可以吗

可以留个联系方式吗？我加你，然后发给你

**Comment by minnie-lin** [comment]
> > > 代码写得很清楚，很容易理解，我已经完成了无监督的代码修改，再次感谢您的工作！
> > 
> > 
> > 你好，请问你修改之后对于MSMT数据集能够很好完成工作吗
> 
> 不好意思，刚看到消息，我的是在MSMT17上实验的，效果还是可以的，和论文里面基本上一致的。我在ClusterContrast中设置如下：1、Freeze patch projection layer trick 2、DBSCAN 0.7 30 6 3、将Adam修改为SGD 优化器

@Trangle12 很奇怪的是我用market数据集完全ok，但是因为换了数据集msmt，需要改一些超参数，就不知道哪里改动的有问题了，map一直在20多，就不变了，还挺着急的，如果有可能的话可以加个联系方式聊一聊吗，或者可以发给我您的修改代码吗？非常冒昧，不好意思。我的联系方式2235947994@qq.com

**Comment by minnie-lin** [comment]
> > > > > 代码写得很清楚，很容易理解，我已经完成了无监督的代码修改，再次感谢您的工作！
> > > > 
> > > > 
> > > > 你好，请问你修改之后对于MSMT数据集能够很好完成工作吗
> > > 
> > > 
> > > 不好意思，刚看到消息，我的是在MSMT17上实验的，效果还是可以的，和论文里面基本上一致的。我在ClusterContrast中设置如下：1、Freeze patch projection layer trick 2、DBSCAN 0.7 30 6 3、将Adam修改为SGD 优化器
> > 
> > 
> > @Trangle12 你好，我也是这么设置的，然后优化器两个都试了，还是很低，很冒昧的想看看你修改后的代码可以吗
> 
> 可以留个联系方式吗？我加你，然后发给你

qq:2235947997

**Comment by abhinavnagpal** [comment]
@Betricy @Trangle12 It will be very helpful if you can provide the code to me as well. Having similar issues with MSMT17 dataset. 
Email: abhinavnagpal12@gmail.com

如果您也可以向我提供代码，那将非常有帮助。 MSMT17 数据集也存在类似问题。

**Comment by Ashh-Z** [comment]
> The code is clearly written and easy to understand, I've finished the unsupervised code changes, thanks again for your work!

Hi, If possible could please point me to the changes required for the unsupervised training setup?
@Trangle12

**Comment by ykding666** [comment]
> The code is clearly written and easy to understand, I've finished the unsupervised code changes, thanks again for your work!

您好，可以求一份无监督的代码吗，ykding@nuaa.edu.cn
